name: default build

on:
  workflow_dispatch:

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install tkinter on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: build with pyinstaller
        run: |
            pyinstaller main.spec

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klik-${{ matrix.os }}
          path: dist/*
